# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(217, 235, 247);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 390, 471, 191))
        self.groupBox.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(188, 128, 233, 255), stop:1 rgba(255, 255, 255, 255));")
        self.groupBox.setObjectName("groupBox")
        self.btnDel = QtWidgets.QPushButton(self.groupBox)
        self.btnDel.setGeometry(QtCore.QRect(270, 90, 159, 30))
        self.btnDel.setMinimumSize(QtCore.QSize(50, 30))
        self.btnDel.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(133, 185, 224, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btnDel.setObjectName("btnDel")
        self.btnChoosefile = QtWidgets.QPushButton(self.groupBox)
        self.btnChoosefile.setGeometry(QtCore.QRect(20, 40, 159, 30))
        self.btnChoosefile.setMinimumSize(QtCore.QSize(50, 30))
        self.btnChoosefile.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(133, 185, 224, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btnChoosefile.setObjectName("btnChoosefile")
        self.btnRecovery = QtWidgets.QPushButton(self.groupBox)
        self.btnRecovery.setGeometry(QtCore.QRect(20, 90, 159, 30))
        self.btnRecovery.setMinimumSize(QtCore.QSize(50, 30))
        self.btnRecovery.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(133, 185, 224, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btnRecovery.setObjectName("btnRecovery")
        self.btnControl = QtWidgets.QPushButton(self.groupBox)
        self.btnControl.setGeometry(QtCore.QRect(160, 140, 159, 30))
        self.btnControl.setMinimumSize(QtCore.QSize(50, 30))
        self.btnControl.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(133, 185, 224, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btnControl.setObjectName("btnControl")
        self.btnChoosedir = QtWidgets.QPushButton(self.groupBox)
        self.btnChoosedir.setGeometry(QtCore.QRect(270, 40, 159, 30))
        self.btnChoosedir.setMinimumSize(QtCore.QSize(50, 30))
        self.btnChoosedir.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(133, 185, 224, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btnChoosedir.setObjectName("btnChoosedir")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 30, 351, 41))
        self.label.setStyleSheet("color: rgb(11, 115, 40);\n"
"")
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(660, 540, 135, 30))
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 30))
        self.pushButton_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(133, 185, 224, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(390, 340, 159, 30))
        self.pushButton.setMinimumSize(QtCore.QSize(50, 30))
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(133, 185, 224, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(590, 340, 159, 30))
        self.pushButton_3.setMinimumSize(QtCore.QSize(50, 30))
        self.pushButton_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(133, 185, 224, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 540, 135, 30))
        self.pushButton_2.setMinimumSize(QtCore.QSize(50, 30))
        self.pushButton_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(133, 185, 224, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton_2.setObjectName("pushButton_2")
        self.listWidgetChoose = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetChoose.setGeometry(QtCore.QRect(10, 10, 321, 361))
        self.listWidgetChoose.setObjectName("listWidgetChoose")
        self.listWidgetControl = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetControl.setGeometry(QtCore.QRect(350, 70, 431, 251))
        self.listWidgetControl.setObjectName("listWidgetControl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Контроль целостности"))
        self.groupBox.setTitle(_translate("MainWindow", "Действия с файлами"))
        self.btnDel.setText(_translate("MainWindow", "Удалить из списка"))
        self.btnChoosefile.setText(_translate("MainWindow", "Выбрать файл"))
        self.btnRecovery.setText(_translate("MainWindow", "Восстановить файлы"))
        self.btnControl.setText(_translate("MainWindow", "Добавить на КЦ"))
        self.btnChoosedir.setText(_translate("MainWindow", "Выбрать каталог"))
        self.label.setText(_translate("MainWindow", "           Следующие файлы добавлены на КЦ"))
        self.pushButton_4.setText(_translate("MainWindow", "ОК"))
        self.pushButton.setText(_translate("MainWindow", "Снять с КЦ"))
        self.pushButton_3.setText(_translate("MainWindow", "Проверить КЦ"))
        self.pushButton_2.setText(_translate("MainWindow", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
